#!/bin/bash

WORKING_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
#WORKING_DIR="/home/iot-devkit/VSCRemote_Workspace2"

BUILD_FOLDER=${WORKING_DIR}/build
EXEC_FOLDER=${WORKING_DIR}/bin
EXEC_NAME=CmakeTest

echo -e "\e[33mBuilding Executable...."
cd ${BUILD_FOLDER}
cmake ..
make -j

if [ "$?" -ne "0" ]; then
  echo -e "\e[33mMake Failed. Exiting Prorgam..."
  echo -e "\e[39m \n"
  exit 1
fi


echo -e "\e[32mDone building ${EXEC_NAME} !"

echo -e "\e[39m"

cd ..

